# Generated by Django 4.2.4 on 2023-09-17 11:32

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_at'], 'verbose_name': 'ارتباط با ما', 'verbose_name_plural': 'ارتباط با ما'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=350, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن درست نیست!', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
    ]
