# Generated by Django 4.2.4 on 2023-09-16 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'UnSuccess'), (1, 'SuccessFull')], null=True, verbose_name='status')),
                ('status_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='status_code')),
                ('ref_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ref_code')),
                ('amount', models.PositiveIntegerField(null=True, verbose_name='amount')),
                ('error_message', models.TextField(blank=True, help_text='در صورت بروز خطا', null=True, verbose_name='error_message')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='shop.order', verbose_name='order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-id'],
            },
        ),
    ]
