# Generated by Django 4.2.4 on 2023-09-17 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_branch_options_alter_brand_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, help_text='در صورت بروز خطا', null=True, verbose_name='پیام ارور'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='shop.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ناموفق'), (1, 'موفق')], null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='کد وضعیت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
