# Generated by Django 4.1.5 on 2023-03-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
    ]
