# Generated by Django 4.1.5 on 2023-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_page_meta_description_en_page_meta_description_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/7', verbose_name='thumbnail'),
        ),
    ]
