# Generated by Django 4.1.5 on 2023-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_page_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/8', verbose_name='thumbnail'),
        ),
    ]
