# Generated by Django 4.1.5 on 2023-08-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_page_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_fa',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_active_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_active_fa',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description_fa',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title_fa',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_fa',
        ),
    ]
