# Generated by Django 4.1.5 on 2023-09-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_remove_page_content_en_remove_page_content_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/9', verbose_name='thumbnail'),
        ),
    ]
