# Generated by Django 4.2.4 on 2023-09-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_page_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='meta description'),
        ),
    ]
