# Generated by Django 4.2.4 on 2023-09-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_page_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('pr', 'پیش\u200c فروش'), ('ou', 'در انبار موجود نیست'), ('in', 'موجود در انبار')], default='in', max_length=2, verbose_name='status'),
        ),
    ]
