# Generated by Django 4.2.4 on 2023-09-17 11:32

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0011_alter_page_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'صفحه', 'verbose_name_plural': 'صفحه\u200cها'},
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='page',
            name='custom_template',
            field=models.BooleanField(default=False, verbose_name='نمونه شخصی\u200cسازی شده'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات برای سئو'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='عنوان برای سئو'),
        ),
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/9', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='page',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
    ]
