# Generated by Django 4.2.4 on 2023-10-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_alter_page_options_alter_page_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/10', verbose_name='تصویر'),
        ),
    ]
