# Generated by Django 4.2.4 on 2023-10-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_alter_page_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('پیش\u200c فروش', 'Pre Order'), ('در انبار موجود نیست', 'Out Stock'), ('موجود در انبار', 'In Stock')], default='موجود در انبار', max_length=32, verbose_name='status'),
        ),
    ]
