# Generated by Django 4.2.4 on 2023-10-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_alter_page_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان'),
        ),
    ]
