# Generated by Django 4.2.4 on 2023-11-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_alter_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/11', verbose_name='تصویر'),
        ),
    ]
