# Generated by Django 4.2.4 on 2023-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_alter_page_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('پیش\u200c فروش', 'پیش\u200c فروش'), ('در انبار موجود نیست', 'در انبار موجود نیست'), ('موجود در انبار', 'موجود در انبار')], default='موجود در انبار', max_length=32, verbose_name='وضعیت'),
        ),
    ]
