# Generated by Django 4.2.4 on 2023-11-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_alter_page_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
        migrations.RemoveField(
            model_name='page',
            name='status',
        ),
        migrations.RemoveField(
            model_name='page',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='page',
            name='thumbnail_alt',
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان'),
        ),
    ]
