# Generated by Django 4.2.4 on 2024-01-04 09:41

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_remove_page_author_remove_page_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت')),
                ('name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('address', models.CharField(max_length=300, verbose_name='ادرس فروشگاه')),
                ('phone_number', models.CharField(max_length=300, verbose_name='تماس فروشگاه')),
                ('logo', models.ImageField(upload_to='base_info/logo/', verbose_name='لوگو فروشگاه')),
                ('logo_alt', models.CharField(max_length=300, verbose_name='متن در صورت نمایش داده نشدن لوگو')),
            ],
            options={
                'verbose_name': 'اطلاعات ابتدایی',
                'verbose_name_plural': 'اطلاعات ابتدایی',
            },
        ),
    ]
