# Generated by Django 4.2.4 on 2024-02-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_baseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_image', models.ImageField(blank=True, null=True, upload_to='landing_images/2024/2', verbose_name='تصویر پایین صفحه')),
                ('button_image_alt', models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر')),
            ],
            options={
                'verbose_name': 'مدیریت صفحه\u200cاصلی',
                'verbose_name_plural': 'مدیریت صفحات اصلی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnderSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_slider_image', models.ImageField(blank=True, null=True, upload_to='landing_images/under_slider2024/2', verbose_name='تصویر زیر اسلیدر')),
                ('under_slider_image_alt', models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر')),
                ('description', models.CharField(max_length=256, verbose_name='توضیحات')),
                ('under_slider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_slider', to='page.landingpage', verbose_name='تصاویر زیر اسلایدر')),
            ],
            options={
                'verbose_name': 'تصویر زیر اسلایدر',
                'verbose_name_plural': 'تصاویر زیر اسلایدر',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(blank=True, upload_to='landing_images/sliders/2024/2', verbose_name='تصویر اسلایدر')),
                ('slider_image_alt', models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر')),
                ('slider_link', models.URLField(null=True, verbose_name='لینک اسلایدر')),
                ('sliders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='page.landingpage', verbose_name='اسلاید\u200cها')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر',
                'verbose_name_plural': 'تصایر اسلایدر',
            },
        ),
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_thumbnail', models.ImageField(blank=True, upload_to='landing_images/icons/2024/2', verbose_name='تصویر آیکون')),
                ('icon_thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر')),
                ('icon_link', models.URLField(null=True, verbose_name='لینک آیکون')),
                ('icon_name', models.CharField(max_length=64, verbose_name='نام آیکون')),
                ('icons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='page.landingpage', verbose_name='آیکون\u200cها')),
            ],
            options={
                'verbose_name': 'آیکون',
                'verbose_name_plural': 'آیکون\u200cها',
            },
        ),
    ]
