# Generated by Django 4.2.4 on 2024-02-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_landingpage_underslider_slider_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='landing_page_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='نام و مشخصات'),
        ),
    ]
