# Generated by Django 4.2.4 on 2024-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_landingpage_landing_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icons',
            name='icon_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='نام آیکون'),
        ),
        migrations.AlterField(
            model_name='underslider',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='توضیحات'),
        ),
    ]
