# Generated by Django 4.2.4 on 2024-02-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_alter_icons_icon_name_alter_underslider_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='underslider',
            name='description',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='button_link',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='quick_access_link',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید دسترسی سریع'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='quick_access_name',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='متن کلید دسترسی سریع'),
        ),
        migrations.AddField(
            model_name='underslider',
            name='under_slider_link',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='button_image_alt',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='landing_page_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='عنوان کلید'),
        ),
    ]
