# Generated by Django 4.2.4 on 2024-02-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_remove_underslider_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='special_desc_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='توضیحات پیشنهاد ویژه ۱'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_desc_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='توضیحات پیشنهاد ویژه ۲'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_desc_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='توضیحات پیشنهاد ویژه ۳'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/2', verbose_name='تصویر پیشنهاد ویژه ۱'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/2', verbose_name='تصویر پیشنهاد ویژه ۲'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/2', verbose_name='تصویر پیشنهاد ویژه ۳'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_link_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید پیشنهاد ویژه ۱'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_link_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید پیشنهاد ویژه ۲'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_link_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید پیشنهاد ویژه ۳'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_title_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='تایتل پیشنهاد ویژه ۱'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_title_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='تایتل پیشنهاد ویژه ۲'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='special_title_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='تایتل پیشنهاد ویژه ۳'),
        ),
    ]
