# Generated by Django 4.2.4 on 2024-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_alter_icons_icon_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icons',
            name='icon_thumbnail',
            field=models.ImageField(blank=True, upload_to='landing_images/icons/2024/4', verbose_name='تصویر آیکون'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='button_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/4', verbose_name='تصویر پایین صفحه'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='special_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/4', verbose_name='تصویر پیشنهاد ویژه ۱'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='special_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/4', verbose_name='تصویر پیشنهاد ویژه ۲'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='special_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/4', verbose_name='تصویر پیشنهاد ویژه ۳'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(blank=True, upload_to='landing_images/sliders/2024/4', verbose_name='تصویر اسلایدر'),
        ),
        migrations.AlterField(
            model_name='underslider',
            name='under_slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/under_slider2024/4', verbose_name='تصویر زیر اسلیدر'),
        ),
    ]
