# Generated by Django 4.2.4 on 2024-04-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_alter_icons_icon_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان کلید')),
                ('link', models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید')),
                ('landing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_menu', to='page.landingpage', verbose_name='لندینگ')),
            ],
            options={
                'verbose_name': 'منوی دسته بندی هدر',
                'verbose_name_plural': 'منوی دسته بندی هدر',
            },
        ),
        migrations.CreateModel(
            name='DownRightMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان کلید')),
                ('link', models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید')),
                ('landing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down_right_menu', to='page.landingpage', verbose_name='لندینگ')),
            ],
            options={
                'verbose_name': 'منوی راست فوتر',
                'verbose_name_plural': 'منوی راست فوتر',
            },
        ),
        migrations.CreateModel(
            name='DownMiddleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان کلید')),
                ('link', models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید')),
                ('landing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down_middle_menu', to='page.landingpage', verbose_name='لندینگ')),
            ],
            options={
                'verbose_name': 'منوی وسط فوتر',
                'verbose_name_plural': 'منوی وسط فوتر',
            },
        ),
        migrations.CreateModel(
            name='DownLeftMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان کلید')),
                ('link', models.CharField(blank=True, max_length=350, null=True, verbose_name='لینک کلید')),
                ('landing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down_left_menu', to='page.landingpage', verbose_name='لندینگ')),
            ],
            options={
                'verbose_name': 'منوی چپ فوتر',
                'verbose_name_plural': 'منوی چپ فوتر',
            },
        ),
    ]
