# Generated by Django 4.2.4 on 2024-04-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_upmenu_downrightmenu_downmiddlemenu_downleftmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='upmenu',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='توضیحات'),
        ),
    ]
