# Generated by Django 4.2.4 on 2024-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_upmenu_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downleftmenu',
            options={'ordering': ('position',), 'verbose_name': 'منوی چپ فوتر', 'verbose_name_plural': 'منوی چپ فوتر'},
        ),
        migrations.AlterModelOptions(
            name='downmiddlemenu',
            options={'ordering': ('position',), 'verbose_name': 'منوی وسط فوتر', 'verbose_name_plural': 'منوی وسط فوتر'},
        ),
        migrations.AlterModelOptions(
            name='downrightmenu',
            options={'ordering': ('position',), 'verbose_name': 'منوی راست فوتر', 'verbose_name_plural': 'منوی راست فوتر'},
        ),
        migrations.AlterModelOptions(
            name='icons',
            options={'ordering': ('position',), 'verbose_name': 'آیکون', 'verbose_name_plural': 'آیکون\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('position',), 'verbose_name': 'تصویر اسلایدر', 'verbose_name_plural': 'تصایر اسلایدر'},
        ),
        migrations.AlterModelOptions(
            name='underslider',
            options={'ordering': ('position',), 'verbose_name': 'تصویر زیر اسلایدر', 'verbose_name_plural': 'تصاویر زیر اسلایدر'},
        ),
        migrations.AlterModelOptions(
            name='upmenu',
            options={'ordering': ('position',), 'verbose_name': 'منوی دسته بندی هدر', 'verbose_name_plural': 'منوی دسته بندی هدر'},
        ),
        migrations.AddField(
            model_name='downleftmenu',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='downmiddlemenu',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='downrightmenu',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='icons',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='slider',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='underslider',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='upmenu',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='icons',
            name='icon_thumbnail',
            field=models.ImageField(blank=True, upload_to='landing_images/icons/2024/5', verbose_name='تصویر آیکون'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='button_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/5', verbose_name='تصویر پایین صفحه'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='special_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/5', verbose_name='تصویر پیشنهاد ویژه ۱'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='special_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/5', verbose_name='تصویر پیشنهاد ویژه ۲'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='special_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/2024/5', verbose_name='تصویر پیشنهاد ویژه ۳'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(blank=True, upload_to='landing_images/sliders/2024/5', verbose_name='تصویر اسلایدر'),
        ),
        migrations.AlterField(
            model_name='underslider',
            name='under_slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing_images/under_slider2024/5', verbose_name='تصویر زیر اسلیدر'),
        ),
    ]
