# Generated by Django 4.2.4 on 2023-09-17 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='حساب کاربر فعال است؟'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='حساب کاربر تایید شده است<'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن درست نیست', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید حساب'),
        ),
    ]
