# Generated by Django 4.2.4 on 2023-09-18 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ایمیل درست نیست', regex='\\b[\\w\\.-]+@[\\w\\.-]+\\.\\w{2,4}\\b')], verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن درست نیست', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن'),
        ),
    ]
