# Generated by Django 4.2.4 on 2023-10-25 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن درست نیست', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن'),
        ),
    ]
