# Generated by Django 4.2.4 on 2023-12-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='شماره ملی'),
        ),
    ]
