# Generated by Django 4.2.4 on 2023-12-12 03:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_national_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=120, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='شهرستان')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس منزل')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='!کد پستی درست نیست', regex='^\\d{10}$')], verbose_name='کد پستی')),
                ('plaque', models.CharField(blank=True, max_length=10, null=True, verbose_name='پلاک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='accounts.useraddress', verbose_name='آدرس'),
        ),
    ]
