# Generated by Django 4.2.4 on 2023-12-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='addresses', to='accounts.useraddress', verbose_name='آدرس\u200cها'),
        ),
    ]
