# Generated by Django 4.2.4 on 2023-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='reciever',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام گیرنده'),
        ),
    ]
