# Generated by Django 4.2.4 on 2023-12-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_useraddress_phone_number_useraddress_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='phone_number',
            new_name='telephone_number',
        ),
    ]
