# Generated by Django 4.2.4 on 2024-01-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_phone_number_useraddress_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='active',
            field=models.BooleanField(default=False, verbose_name='ادرس فعال است ؟'),
        ),
    ]
