# Generated by Django 4.2.4 on 2024-01-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useraddress_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='active',
        ),
    ]
