# Generated by Django 4.2.4 on 2024-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_useraddress_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='حساب کاربر تایید شده است'),
        ),
    ]
