# Generated by Django 4.2.4 on 2024-04-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_is_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='عنوان سطح دسترسی')),
                ('blog_access', models.BooleanField(default=False, verbose_name='دسترسی بلاگ')),
                ('product_access', models.BooleanField(default=False, verbose_name='دسترسی محصولات')),
                ('order_access', models.BooleanField(default=False, verbose_name='دسترسی سفارشات')),
                ('client_access', models.BooleanField(default=False, verbose_name='دسترسی کاربران')),
                ('user_access', models.BooleanField(default=False, verbose_name='دسترسی همکاران')),
            ],
            options={
                'verbose_name': 'دسترسی',
                'verbose_name_plural': 'دسترسی\u200cها',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permission', to='accounts.userpermission', verbose_name='سطح دسترسی'),
        ),
    ]
