from .serializer_base_user import BaseUserSerializer
from .serializer_user_register import UserRegisterSerializer
from .serializer_verify_otp import VerifyOtpSerializer
from .serializer_custom_token import CustomTokenObtainPairSerializer
from .serializer_user_detail import UserDetailSerializer
from .serializer_user_list import UserListSerializer
from .serializer_user_update import UserUpdateSerializer
from .serializer_user_register_email import UserRegisterEmailSerializer
# Address
from .serializer_address_create_update import AddressCreateUpdateSerializer
from .serializer_address_detail import AddressDetailSerializer
from .serializer_address_list import AddressListSerializer
from .serializer_base_address import BaseAddressSerializer, BaseAddressUpdateSerializer

from .serializer_for_invoice import UserInfoForInvoiceSerializer
