# Generated by Django 4.2.4 on 2023-09-17 11:32

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_post_status_alter_postcategory_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.postcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات برای سئو'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='عنوان برای سئو'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/9', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات برای سئو'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='عنوان برای سئو'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='blog.postcategory', verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='message',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='name',
            field=models.CharField(max_length=350, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post', verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.postcomment', verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
    ]
