# Generated by Django 4.2.4 on 2023-09-18 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_post_options_alter_postcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='name',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='جواب پیام است ؟'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments_reply', to='blog.postcomment', verbose_name='پاسخ'),
        ),
    ]
