# Generated by Django 4.2.4 on 2023-10-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_postcomment_email_remove_postcomment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/10', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/10', verbose_name='تصویر'),
        ),
    ]
