# Generated by Django 4.2.4 on 2023-10-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_thumbnail_alter_postcategory_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='status',
        ),
    ]
