# Generated by Django 4.2.4 on 2023-10-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_postcategory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('منتشر شده', 'Publish'), ('انتشار نیافته', 'Review'), ('پیش\u200cنویس\u200cها', 'Pending')], default='پیش\u200cنویس\u200cها', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='status',
            field=models.CharField(choices=[('منتشر شده', 'Publish'), ('انتشار نیافته', 'Review'), ('پیش\u200cنویس\u200cها', 'Pending')], default='پیش\u200cنویس\u200cها', max_length=16, verbose_name='status'),
        ),
    ]
