# Generated by Django 4.2.4 on 2023-10-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_status_alter_postcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('منتشر شده', 'Publish'), ('آرشیو شده', 'Archive'), ('پیش\u200cنویس\u200cها', 'Pending')], default='پیش\u200cنویس\u200cها', max_length=16, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='status',
            field=models.CharField(choices=[('منتشر شده', 'Publish'), ('آرشیو شده', 'Archive'), ('پیش\u200cنویس\u200cها', 'Pending')], default='پیش\u200cنویس\u200cها', max_length=16, verbose_name='وضعیت'),
        ),
    ]
