# Generated by Django 4.2.4 on 2023-10-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_status_alter_postcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان'),
        ),
    ]
