# Generated by Django 4.2.4 on 2023-11-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_title_alter_postcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/11', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/11', verbose_name='تصویر'),
        ),
    ]
