# Generated by Django 4.2.4 on 2023-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_thumbnail_alter_postcategory_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('منتشر شده', 'منتشر شده'), ('آرشیو شده', 'آرشیو شده'), ('پیش\u200cنویس\u200cها', 'پیش\u200cنویس\u200cها')], default='پیش\u200cنویس\u200cها', max_length=16, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='status',
            field=models.CharField(choices=[('منتشر شده', 'منتشر شده'), ('آرشیو شده', 'آرشیو شده'), ('پیش\u200cنویس\u200cها', 'پیش\u200cنویس\u200cها')], default='پیش\u200cنویس\u200cها', max_length=16, verbose_name='وضعیت'),
        ),
    ]
