# Generated by Django 4.2.4 on 2023-11-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_status_alter_postcategory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='parent_category',
        ),
    ]
