# Generated by Django 4.2.4 on 2023-12-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_postcategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/12', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/12', verbose_name='تصویر'),
        ),
    ]
