# Generated by Django 4.2.4 on 2023-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_thumbnail_alter_postcategory_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='thumbnail_alt',
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان'),
        ),
    ]
