# Generated by Django 4.2.4 on 2023-12-30 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_postcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='rate',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='امتیاز'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='subject',
            field=models.CharField(default=1, max_length=255, verbose_name='موضوع'),
            preserve_default=False,
        ),
    ]
