# Generated by Django 4.2.4 on 2023-12-30 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_postcomment_rate_postcomment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'امتیاز باید حداقل 1 باشد.'), django.core.validators.MaxValueValidator(5, 'امتیاز باید حداکثر 5 باشد.')], verbose_name='امتیاز'),
        ),
    ]
