# Generated by Django 4.2.4 on 2023-12-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_postcomment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='subject',
        ),
    ]
