# Generated by Django 4.2.4 on 2024-01-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_postcomment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2024/1', verbose_name='تصویر'),
        ),
    ]
