# Generated by Django 4.2.4 on 2024-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'منتشر شده'), (1, 'آرشیو شده'), (2, 'پیش\u200cنویس\u200cها')], default=2, verbose_name='وضعیت'),
        ),
    ]
