# Generated by Django 4.2.4 on 2023-09-16 10:44

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='thumbnail')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='thumbnail alt')),
                ('inventory', models.BooleanField(default=False, verbose_name='inventory')),
                ('extra_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='extra_price')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='thumbnail')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='thumbnail alt')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='country')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('pr', 'پیش\u200c فروش'), ('ou', 'در انبار موجود نیست'), ('in', 'موجود در انبار')], default='in', max_length=2, verbose_name='status')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('type_discount', models.PositiveSmallIntegerField(choices=[(0, 'Percentage'), (1, 'Stable')], verbose_name='type_discount')),
                ('type_action', models.PositiveSmallIntegerField(choices=[(0, 'Single'), (1, 'Overall')], verbose_name='type_action')),
                ('percentage', models.IntegerField(blank=True, default=0, null=True, verbose_name='percentage')),
                ('amount_discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='amount_discount')),
                ('expired_date', models.DateTimeField(blank=True, null=True, verbose_name='expired_date')),
                ('expired_date_jalali', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='expired_date_jalali')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='thumbnail')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='thumbnail alt')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'در انتظار پرداخت'), (1, 'پرداخت موفق'), (2, 'در حال انجام'), (3, 'تکمیل شده')], default=0, verbose_name='status')),
                ('consistency_code', models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='consistency_code')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email_sent')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='sms_sent')),
                ('complete_date', models.DateTimeField(blank=True, null=True, verbose_name='complete_date')),
                ('province', models.CharField(blank=True, max_length=120, null=True, verbose_name='province')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='city')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='!کد پستی درست نیست', regex='^\\d{10}$')], verbose_name='postal_code')),
                ('total_paid_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='total_paid_price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('meta_title', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('status', models.CharField(choices=[('pr', 'پیش\u200c فروش'), ('ou', 'در انبار موجود نیست'), ('in', 'موجود در انبار')], default='in', max_length=2, verbose_name='status')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/9', verbose_name='thumbnail')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='thumbnail alt')),
                ('main_price', models.PositiveIntegerField(default=0, verbose_name='main_price')),
                ('discount_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='discount_price')),
                ('inventory', models.IntegerField(verbose_name='inventory')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='balance')),
                ('balance_percentage', models.IntegerField(blank=True, default=0, null=True, verbose_name='balance_percentage')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('priority', models.PositiveBigIntegerField(default=0)),
                ('primary_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_suggestion', to='shop.product', verbose_name='primary')),
                ('suggestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suggestion', to='shop.product', verbose_name='suggestions')),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
                'ordering': ['primary_product', '-priority'],
                'unique_together': {('primary_product', 'suggestions')},
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='thumbnail')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='thumbnail alt')),
                ('type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('option', 'Option')], default='text', max_length=32)),
                ('required', models.BooleanField(default=False)),
                ('options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='options', to='shop.option', verbose_name='options')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='shop.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductsCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='thumbnail')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='thumbnail alt')),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_collections', to='shop.brand', verbose_name='brands')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='product_collections', to='shop.productscollections', verbose_name='collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='product_options', to='shop.option', verbose_name='options'),
        ),
        migrations.AddField(
            model_name='product',
            name='suggestions',
            field=models.ManyToManyField(blank=True, through='shop.Suggestion', to='shop.product', verbose_name='suggestions'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products_tags', to='shop.producttag', verbose_name='tags'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('main_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='main_price')),
                ('paid_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='paid_price')),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_items', to='shop.branch', verbose_name='branches')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order', verbose_name='orders')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.product', verbose_name='product_items')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ('-orders', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('pr', 'پیش\u200c فروش'), ('ou', 'در انبار موجود نیست'), ('in', 'موجود در انبار')], default='in', max_length=2, verbose_name='status')),
                ('name', models.CharField(max_length=350, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('rate', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'امتیاز باید حداقل 1 باشد.'), django.core.validators.MaxValueValidator(5, 'امتیاز باید حداکثر 5 باشد.')], verbose_name='rate')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='shop.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='shop_produc_title_4a03b1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['inventory'], name='shop_produc_invento_aea8da_idx'),
        ),
    ]
