# Generated by Django 4.2.4 on 2023-09-17 11:32

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-id'], 'verbose_name': 'شعبه', 'verbose_name_plural': 'شعبه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-id'], 'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-id'], 'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-id'], 'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-orders', '-created_at'), 'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productscollections',
            options={'ordering': ['-id'], 'verbose_name': 'کالکشن', 'verbose_name_plural': 'کالکشن\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ['-id'], 'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['primary_product', '-priority'], 'verbose_name': 'پیشنهاد محصول', 'verbose_name_plural': 'پیشنهادات محصول'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='extra_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='هزینه اضافی شعبه'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='inventory',
            field=models.BooleanField(default=False, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=350, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='shop.product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'امتیاز باید حداقل 1 باشد.'), django.core.validators.MaxValueValidator(5, 'امتیاز باید حداکثر 5 باشد.')], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount_discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ میلادی انقضا کد'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expired_date_jalali',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شمسی انقضا کد'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type_action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'تکی'), (1, 'همگانی')], verbose_name='نوع اعمال'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type_discount',
            field=models.PositiveSmallIntegerField(choices=[(0, 'درصدی'), (1, 'ثابت')], verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='option',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='option',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل خرید'),
        ),
        migrations.AlterField(
            model_name='order',
            name='consistency_code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='کد پیگیری سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضحیات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال ایمیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='!کد پستی درست نیست', regex='^\\d{10}$')], verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sms_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'در انتظار پرداخت'), (1, 'پرداخت موفق'), (2, 'در حال انجام'), (3, 'تکمیل شده')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_paid_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='هزینه نهایی سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='branches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_items', to='shop.branch', verbose_name='شعبه\u200cها'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='main_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=' هزینه\u200cی اصلی آیتم'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order', verbose_name='سفارشات'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='paid_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=' هزینه\u200cی پرداختی آیتم'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='محصولات', to='shop.product', verbose_name='product_items'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد سافرش محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='product_collections', to='shop.productscollections', verbose_name='کالکشن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(verbose_name='تعداد موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه اصلی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات برای سئو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='عنوان برای سئو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='product_options', to='shop.option', verbose_name='تنظیمات اضافی برای محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suggestions',
            field=models.ManyToManyField(blank=True, through='shop.Suggestion', to='shop.product', verbose_name='پیشنهادات برای محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products_tags', to='shop.producttag', verbose_name='ویژگی\u200cهای اضافی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/9', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='productscollections',
            name='brands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_collections', to='shop.brand', verbose_name='برند\u200cها'),
        ),
        migrations.AlterField(
            model_name='productscollections',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productscollections',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productscollections',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='productscollections',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='options', to='shop.option', verbose_name='تنظیمات'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='shop.product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='required',
            field=models.BooleanField(default=False, verbose_name='آیا محصول ویژگی لازم دارد؟'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/9', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='type',
            field=models.CharField(choices=[('متنی', 'Text'), ('عددی', 'Integer'), ('اعشاری', 'Float'), ('تنظیمات بیشتر', 'Option')], default='متنی', max_length=32, verbose_name='نوع ویژگی'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='primary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_suggestion', to='shop.product', verbose_name='پیشنهاد اصلی'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='priority',
            field=models.PositiveBigIntegerField(default=0, verbose_name='اولیت پیشنهادی این محصول برای کاربر'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suggestion', to='shop.product', verbose_name='سایر پیشنهاد\u200cها'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='درصد موجودی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت'),
        ),
    ]
