# Generated by Django 4.2.4 on 2023-09-21 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_comment_email_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_branch', to='shop.product', verbose_name='محصولات'),
        ),
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='product_branches', to='shop.branch', verbose_name='شعبه\u200cهای سفارش'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی شعبه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی محصول'),
        ),
    ]
