# Generated by Django 4.2.4 on 2023-10-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_branch_thumbnail_alter_brand_thumbnail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
