# Generated by Django 4.2.4 on 2023-10-06 10:01

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_deadline',
            field=models.BooleanField(default=False, verbose_name='محصول قیمت موقت دارد؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_expired_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شمسی انقضا قیمت'),
        ),
    ]
