# Generated by Django 4.2.4 on 2023-10-06 10:48

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_price_deadline_product_price_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_expired_date_jalali',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شمسی انقضا قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_expired_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ میلادی انقضا قیمت'),
        ),
    ]
