# Generated by Django 4.2.4 on 2023-10-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_price_expired_date_jalali_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='status',
        ),
    ]
