# Generated by Django 4.2.4 on 2023-10-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_discount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='هزینه اضافی شعبه'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='branches',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تخفیف شعبه'),
        ),
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.CharField(choices=[('kar', 'کرج'), ('teh', 'تهران')], default='kar', max_length=3, verbose_name='شعبه'),
        ),
    ]
