# Generated by Django 4.2.4 on 2023-10-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_extra_price_remove_product_branches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
