# Generated by Django 4.2.4 on 2023-10-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'تیپاکس'), (1, 'پست پیش\u200cتاز'), (2, 'تخویل حضوری')], default=1, verbose_name='روش ارسال'),
        ),
    ]
