# Generated by Django 4.2.4 on 2023-10-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_delivery_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_paid_price',
        ),
    ]
