# Generated by Django 4.2.4 on 2023-10-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_order_total_paid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='inventory',
        ),
    ]
