# Generated by Django 4.2.4 on 2023-10-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_branch_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pre_order', 'پیش\u200c فروش'), ('out_stock', 'در انبار موجود نیست'), ('in_stock', 'موجود در انبار')], default='in_stock', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pre_order', 'پیش\u200c فروش'), ('out_stock', 'در انبار موجود نیست'), ('in_stock', 'موجود در انبار')], default='in_stock', max_length=10, verbose_name='status'),
        ),
    ]
