# Generated by Django 4.2.4 on 2023-10-31 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_comment_status_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='description',
        ),
        migrations.RemoveField(
            model_name='option',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='option',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='option',
            name='thumbnail_alt',
        ),
        migrations.RemoveField(
            model_name='option',
            name='title',
        ),
        migrations.AddField(
            model_name='option',
            name='colors',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='رنگ\u200cبندی محصول'),
        ),
        migrations.AddField(
            model_name='option',
            name='guarantee',
            field=models.PositiveSmallIntegerField(blank=True, default=90, null=True, verbose_name='گارانتی'),
        ),
        migrations.AddField(
            model_name='option',
            name='insurance',
            field=models.PositiveSmallIntegerField(blank=True, default=7, null=True, verbose_name='ضمانت بازگشت'),
        ),
        migrations.AddField(
            model_name='option',
            name='special_tag',
            field=models.CharField(choices=[('تعداد محدود', 'Limited'), ('تخفیف ویژه', 'Special'), ('جدید', 'New'), ('فروش فوق\u200cالعاده', 'Bestseller')], default='جدید', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='branches',
            field=models.CharField(choices=[('شمال', 'Shomal'), ('تهران', 'Tehran')], default='تهران', max_length=16, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='primary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_suggestion', to='shop.product', verbose_name='پیشنهاد و ست اصلی'),
        ),
    ]
