# Generated by Django 4.2.4 on 2023-10-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_option_description_remove_option_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('پیش\u200c فروش', 'Pre Order'), ('در انبار موجود نیست', 'Out Stock'), ('موجود در انبار', 'In Stock')], default='موجود در انبار', max_length=32, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='option',
            name='special_tag',
            field=models.CharField(choices=[('تعداد محدود', 'Limited'), ('تخفیف ویژه', 'Special'), ('جدید', 'New'), ('فروش فوق\u200cالعاده', 'Bestseller')], default='جدید', max_length=32, verbose_name='تگ مخصوص'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('پیش\u200c فروش', 'Pre Order'), ('در انبار موجود نیست', 'Out Stock'), ('موجود در انبار', 'In Stock')], default='موجود در انبار', max_length=32, verbose_name='وضعیت'),
        ),
    ]
