# Generated by Django 4.2.4 on 2023-10-31 14:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_comment_status_alter_option_special_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='option',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='option',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/10', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='option',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
        migrations.AddField(
            model_name='option',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='productscollections',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='عنوان'),
        ),
    ]
