# Generated by Django 4.2.4 on 2023-10-31 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_option_description_option_slug_option_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='options',
        ),
        migrations.AddField(
            model_name='option',
            name='option_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_products', to='shop.product', verbose_name='تنظیمات'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.AlterField(
            model_name='producttag',
            name='type',
            field=models.CharField(choices=[('متنی', 'Text'), ('عددی', 'Integer')], default='متنی', max_length=32, verbose_name='نوع ویژگی'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_collections', to='shop.productscollections', verbose_name='کالکشن'),
        ),
    ]
