# Generated by Django 4.2.4 on 2023-10-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_producttag_options_option_option_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option_products',
        ),
    ]
