# Generated by Django 4.2.4 on 2023-11-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_option_option_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/11', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/11', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='option',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/11', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/11', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productscollections',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/11', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/11', verbose_name='تصویر'),
        ),
    ]
