# Generated by Django 4.2.4 on 2023-11-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_branch_thumbnail_alter_brand_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='description',
        ),
        migrations.RemoveField(
            model_name='option',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='option',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='option',
            name='thumbnail_alt',
        ),
        migrations.RemoveField(
            model_name='option',
            name='title',
        ),
    ]
