# Generated by Django 4.2.4 on 2023-11-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_option_description_remove_option_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='has_guarantee',
            field=models.BooleanField(default=True, verbose_name='گارانتی دارد؟'),
        ),
        migrations.AddField(
            model_name='option',
            name='has_insurance',
            field=models.BooleanField(default=True, verbose_name='ضمانت بازگشت دارد؟'),
        ),
        migrations.AlterField(
            model_name='option',
            name='colors',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='رنگ\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='option',
            name='insurance',
            field=models.PositiveSmallIntegerField(blank=True, default=7, null=True, verbose_name='تعداد روز برای ضمانت بازگشت کالا'),
        ),
    ]
