# Generated by Django 4.2.4 on 2023-11-02 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_option_has_guarantee_option_has_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='shop.option', verbose_name='تنظیمات اضافه برای محصول'),
        ),
    ]
