# Generated by Django 4.2.4 on 2023-11-02 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_product_options_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='shop.option', verbose_name='تنظیمات برای محصولات'),
        ),
    ]
