# Generated by Django 4.2.4 on 2023-11-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('shop', '0027_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='colors',
        ),
        migrations.AddField(
            model_name='option',
            name='colors',
            field=models.ManyToManyField(blank=True, max_length=12, to='utils.colors', verbose_name='رنگ\u200cبندی'),
        ),
    ]
