# Generated by Django 4.2.4 on 2023-11-02 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_option_colors_option_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, max_length=12, unique=True, verbose_name='نام رنگ')),
                ('options', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_colors', to='shop.option', verbose_name='تنظیمات')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='option',
            name='colors',
            field=models.ManyToManyField(blank=True, max_length=12, related_name='option_colors', to='shop.colors', verbose_name='رنگ\u200cبندی'),
        ),
    ]
