# Generated by Django 4.2.4 on 2023-11-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_colors_alter_option_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='products',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='options',
        ),
        migrations.RemoveField(
            model_name='option',
            name='colors',
        ),
        migrations.AddField(
            model_name='colors',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='shop.product', verbose_name='رنگ محصولات'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('پیش\u200c فروش', 'پیش\u200c فروش'), ('در انبار موجود نیست', 'در انبار موجود نیست'), ('موجود در انبار', 'موجود در انبار')], default='موجود در انبار', max_length=32, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('پیش\u200c فروش', 'پیش\u200c فروش'), ('در انبار موجود نیست', 'در انبار موجود نیست'), ('موجود در انبار', 'موجود در انبار')], default='موجود در انبار', max_length=32, verbose_name='وضعیت'),
        ),
    ]
