# Generated by Django 4.2.4 on 2023-11-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_branch_extra_price_remove_branch_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='shop.product', verbose_name='رنگ'),
        ),
        migrations.AlterUniqueTogether(
            name='colors',
            unique_together={('product_color', 'color')},
        ),
    ]
