# Generated by Django 4.2.4 on 2023-11-04 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_colors_color_alter_colors_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colors',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='option',
            name='colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shop.colors', verbose_name='رنگ\u200cها'),
        ),
        migrations.AddField(
            model_name='option',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='shop.product', verbose_name='رنگ محصولات'),
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='product_color',
        ),
    ]
