# Generated by Django 4.2.4 on 2023-11-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_colors_unique_together_option_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='guarantee',
        ),
        migrations.RemoveField(
            model_name='option',
            name='has_guarantee',
        ),
        migrations.RemoveField(
            model_name='option',
            name='has_insurance',
        ),
        migrations.RemoveField(
            model_name='option',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='option',
            name='special_tag',
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.PositiveSmallIntegerField(blank=True, default=90, null=True, verbose_name='گارانتی'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_guarantee',
            field=models.BooleanField(default=True, verbose_name='گارانتی دارد؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_insurance',
            field=models.BooleanField(default=True, verbose_name='ضمانت بازگشت دارد؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='insurance',
            field=models.PositiveSmallIntegerField(blank=True, default=7, null=True, verbose_name='تعداد روز برای ضمانت بازگشت کالا'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_tag',
            field=models.CharField(choices=[('تعداد محدود', 'تعداد محدود'), ('تخفیف ویژه', 'تخفیف ویژه'), ('جدید', 'جدید'), ('فروش فوق\u200cالعاده', 'فروش فوق\u200cالعاده')], default='جدید', max_length=32, verbose_name='تگ مخصوص'),
        ),
    ]
