# Generated by Django 4.2.4 on 2023-11-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_remove_option_guarantee_remove_option_has_guarantee_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_invento_aea8da_idx',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='thumbnail_alt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_branch', to='shop.product', verbose_name='شعبه محصولات'),
        ),
        migrations.AddField(
            model_name='branch',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی محصول'),
        ),
        migrations.AddField(
            model_name='option',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='shop.branch', verbose_name='شعبه\u200cها'),
        ),
        migrations.AddField(
            model_name='product',
            name='deadline_price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه تخفیف زمانی'),
        ),
    ]
