# Generated by Django 4.2.4 on 2023-11-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_product_shop_produc_invento_aea8da_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='colors',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='shop.product', verbose_name='رنگ محصولات'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
