# Generated by Django 4.2.4 on 2023-11-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_remove_product_options_colors_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.branch'),
        ),
        migrations.AddField(
            model_name='colors',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.colors'),
        ),
    ]
