# Generated by Django 4.2.4 on 2023-11-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_branch_branches_colors_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='thumbnail_alt',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='type',
        ),
        migrations.AddField(
            model_name='producttag',
            name='content',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='products_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.producttag'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='required',
            field=models.BooleanField(default=False, verbose_name='آیا محصول این تگ را  لازم دارد؟'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='مشخصه'),
        ),
    ]
