# Generated by Django 4.2.4 on 2023-11-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_producttag_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
