# Generated by Django 4.2.4 on 2023-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_remove_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='color_name',
            field=models.CharField(blank=True, max_length=12, verbose_name='نام رنگ'),
        ),
    ]
