# Generated by Django 4.2.4 on 2023-11-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_colors_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='slug',
        ),
    ]
