# Generated by Django 4.2.4 on 2023-11-04 17:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_remove_branch_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodcut_review',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='بررسی تخصصی'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='basic_gallery/images/2023/11', verbose_name='تصویر')),
                ('image_alt', models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر')),
                ('product_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='تصاویر')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری\u200cها',
            },
        ),
    ]
