# Generated by Django 4.2.4 on 2023-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_product_prodcut_review_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='موجودی محصول'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان'),
        ),
    ]
