# Generated by Django 4.2.4 on 2023-11-05 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_branch_inventory_alter_branch_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='تگ\u200c')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ['-id'], 'verbose_name': 'تگ', 'verbose_name_plural': 'تگ\u200cها'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_product',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='title',
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=350, verbose_name='نام شعبه'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='required',
            field=models.BooleanField(default=False, verbose_name='آیا محصول این تگ را لازم دارد؟'),
        ),
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.colors')),
                ('product_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='shop.product', verbose_name='رنگ محصولات')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='موجودی محصول')),
                ('branch_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_branch', to='shop.product', verbose_name='شعبه محصولات')),
                ('branches', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.branch')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبه\u200cها',
                'ordering': ['-id'],
            },
        ),
    ]
