# Generated by Django 4.2.4 on 2023-11-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_tag_alter_producttag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
