# Generated by Django 4.2.4 on 2023-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='product_colors', to='shop.colors', verbose_name='رنگ\u200cها'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.DeleteModel(
            name='ProductColors',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='product_collections', to='shop.productscollections', verbose_name='کالکشن'),
        ),
    ]
