# Generated by Django 4.2.4 on 2023-11-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_product_colors_remove_product_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_review',
            new_name='product_review',
        ),
        migrations.AlterField(
            model_name='product',
            name='deadline_price',
            field=models.PositiveIntegerField(verbose_name='هزینه تخفیف زمانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_price',
            field=models.PositiveIntegerField(verbose_name='هزینه اصلی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=64, verbose_name='عنوان'),
        ),
    ]
