# Generated by Django 4.2.4 on 2023-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_alter_producttag_products_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/11', verbose_name='تصویر شاخص'),
        ),
    ]
