# Generated by Django 4.2.4 on 2023-11-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscollections',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productscollections',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='productscollections',
            name='thumbnail_alt',
        ),
        migrations.AlterField(
            model_name='productscollections',
            name='brands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_collections', to='shop.brand', verbose_name='برند\u200cها'),
        ),
        migrations.AlterField(
            model_name='productscollections',
            name='title',
            field=models.CharField(max_length=64, verbose_name='عنوان'),
        ),
    ]
