# Generated by Django 4.2.4 on 2023-11-05 19:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
            ('shop', '0049_remove_productscollections_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'تگ ویژه',
                'verbose_name_plural': 'تگ\u200cهای ویژه',
                'ordering': ['-id'],
            },
        ),
    ]
