# Generated by Django 4.2.4 on 2023-11-05 20:29

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_specialtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='ویژگی\u200cهای اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deadline_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_price',
            field=models.PositiveIntegerField(verbose_name='قیمت اصلی محصول'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_tag',
        ),
        migrations.AlterField(
            model_name='specialtag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_tag',
            field=models.ManyToManyField(blank=True, related_name='product_special_tag', to='shop.specialtag', verbose_name='تگ مخصوص'),
        ),
    ]
