# Generated by Django 4.2.4 on 2023-11-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_colors_color_alter_product_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='guarantee',
            field=models.CharField(blank=True, default='گارانتی ۲۴ ماهه علیزاده', max_length=256, null=True, verbose_name='گارانتی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insurance',
            field=models.CharField(blank=True, default='۷ روز ضمانت بازگشت وجه', max_length=256, null=True, verbose_name='تعداد روز برای ضمانت بازگشت کالا'),
        ),
    ]
