# Generated by Django 4.2.4 on 2023-11-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_alter_product_guarantee_alter_product_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='نام مشخصه')),
            ],
            options={
                'verbose_name': 'مشخصات ظاهری',
                'verbose_name_plural': 'مشخصات ظاهری',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=350, null=True, verbose_name='توضیحات')),
                ('required', models.BooleanField(default=False, verbose_name='آیا محصول این تگ را لازم دارد؟')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='shop.product', verbose_name='محصولات')),
                ('products_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.attributestyle', verbose_name='مشخصه ظاهری')),
            ],
            options={
                'verbose_name': 'مشخصات ظاهری',
                'verbose_name_plural': 'مشخصات ظاهری',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
