# Generated by Django 4.2.4 on 2023-11-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_attributestyle_productattributestyle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='set_watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_set_watch', to='shop.product', verbose_name='محصول ست این ساعت'),
        ),
        migrations.AlterField(
            model_name='productbranch',
            name='branches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.branch', verbose_name='شعبه'),
        ),
    ]
