# Generated by Django 4.2.4 on 2023-11-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_remove_product_collection_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='نام مشخصه')),
            ],
            options={
                'verbose_name': 'مشخصات فنی و تولید',
                'verbose_name_plural': 'مشخصات فنی و تولید',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=350, null=True, verbose_name='توضیحات')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tech_attr', to='shop.product', verbose_name='محصولات')),
                ('products_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.attributetech', verbose_name='مشخصه فنی و تولید')),
            ],
            options={
                'verbose_name': 'مشخصات فنی و تولید',
                'verbose_name_plural': 'مشخصات فنی و تولید',
                'ordering': ['-id'],
            },
        ),
    ]
