# Generated by Django 4.2.4 on 2023-11-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_attributetech_productattributetech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributestyle',
            name='required',
        ),
    ]
