# Generated by Django 4.2.4 on 2023-11-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_remove_productattributestyle_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='مشخصه')),
            ],
            options={
                'verbose_name': 'مشخصات فنی و تولید',
                'verbose_name_plural': 'مشخصات فنی و تولید',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=350, null=True, verbose_name='توضیحات')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='shop.product', verbose_name='محصولات')),
                ('products_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.attribute')),
            ],
            options={
                'verbose_name': 'مشخصات فنی و تولید',
                'verbose_name_plural': 'مشخصات فنی و تولید',
                'ordering': ['-id'],
            },
        ),
    ]
