# Generated by Django 4.2.4 on 2023-11-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_attribute_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='products_attribute',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
