# Generated by Django 4.2.4 on 2023-11-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_remove_productattribute_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='product_collections', to='shop.productscollections', verbose_name='کالکشن\u200cها'),
        ),
    ]
