# Generated by Django 4.2.4 on 2023-11-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_product_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='thumbnail_alt',
        ),
    ]
