# Generated by Django 4.2.4 on 2023-11-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_remove_brand_thumbnail_remove_brand_thumbnail_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscollections',
            name='brands',
        ),
        migrations.AddField(
            model_name='productscollections',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='product_collections', to='shop.brand', verbose_name='برند\u200cها'),
        ),
    ]
