# Generated by Django 4.2.4 on 2023-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_remove_productscollections_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=128, verbose_name='عنوان'),
        ),
    ]
