# Generated by Django 4.2.4 on 2023-11-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=64, verbose_name='نام شعبه'),
        ),
    ]
