# Generated by Django 4.2.4 on 2023-11-12 06:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_product_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'ویژگی اصلی',
                'verbose_name_plural': 'ویژگی\u200cهای اصلی',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا'),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, related_name='product_attributes', to='shop.attribute', verbose_name='ویژگی\u200cهای اصلی'),
        ),
    ]
