# Generated by Django 4.2.4 on 2023-11-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_attribute_alter_product_content_product_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributestyle',
            options={'ordering': ['-id'], 'verbose_name': 'مشخصات کلی', 'verbose_name_plural': 'مشخصات کلی'},
        ),
        migrations.AlterField(
            model_name='productattributestyle',
            name='products_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.attributestyle', verbose_name='مشخصه'),
        ),
    ]
