# Generated by Django 4.2.4 on 2023-11-16 07:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_alter_productattributestyle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributestyle',
            options={'ordering': ['-id'], 'verbose_name': 'مشخصات کلی', 'verbose_name_plural': 'مشخصات کلی'},
        ),
        migrations.AlterModelOptions(
            name='productscollections',
            options={'ordering': ['-id'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.AlterField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='product_collections', to='shop.productscollections', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='ویژگی\u200cهای اصلی'),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
