# Generated by Django 4.2.4 on 2023-11-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_alter_attributestyle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deadline_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تخفیف موقت'),
        ),
    ]
