# Generated by Django 4.2.4 on 2023-11-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_alter_product_deadline_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('در انتظار تأیید', 'در انتظار تأیید'), ('منتشر شده', 'منتشر شده')], default='در انتظار تأیید', max_length=32, verbose_name='وضعیت'),
        ),
    ]
