# Generated by Django 4.2.4 on 2023-11-26 05:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarantee_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='شرایط گارانتی'),
        ),
    ]
