# Generated by Django 4.2.4 on 2023-11-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_product_guarantee_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.BigIntegerField(default=0),
        ),
    ]
