# Generated by Django 4.2.4 on 2023-12-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_alter_gallery_image_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/12', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='brand',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='متن در صورت نمایش داده نشدن تصویر'),
        ),
    ]
