# Generated by Django 4.2.4 on 2023-12-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_brand_thumbnail_brand_thumbnail_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='province',
        ),
    ]
