# Generated by Django 4.2.4 on 2023-12-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد سفارش محصول'),
        ),
    ]
