# Generated by Django 4.2.4 on 2023-12-12 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-orders', '-created_at'), 'verbose_name': 'محصول سفارش', 'verbose_name_plural': 'محصولات سفارش'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='branches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_items', to='shop.branch', verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='main_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='هزینه\u200cی اصلی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order', verbose_name='شناسه سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='paid_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='هزینه\u200cی پرداختی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_items', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد سفارش'),
        ),
    ]
