# Generated by Django 4.2.4 on 2023-12-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0079_alter_orderitem_options_alter_orderitem_branches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'در انتظار پرداخت'), (1, 'پرداخت موفق'), (2, 'در حال انجام'), (3, 'تکمیل شده'), (4, 'مرجوع شده')], default=0, verbose_name='وضعیت'),
        ),
    ]
