# Generated by Django 4.2.4 on 2023-12-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscollections',
            name='brands',
        ),
        migrations.AddField(
            model_name='productscollections',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_parent', to='shop.productscollections', verbose_name='دسته بندی مادر'),
        ),
    ]
