# Generated by Django 4.2.4 on 2023-12-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_remove_productscollections_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_guarantee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_insurance',
        ),
    ]
