# Generated by Django 4.2.4 on 2023-12-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_remove_product_has_guarantee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default=0, max_length=255, verbose_name='موضوع'),
            preserve_default=False,
        ),
    ]
