# Generated by Django 4.2.4 on 2023-12-30 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0083_comment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'امتیاز باید حداقل 1 باشد.'), django.core.validators.MaxValueValidator(5, 'امتیاز باید حداکثر 5 باشد.')], verbose_name='امتیاز'),
            preserve_default=False,
        ),
    ]
