# Generated by Django 4.2.4 on 2023-12-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_alter_comment_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('منتشر شده', 'منتشر شده'), ('آرشیو شده', 'آرشیو شده'), ('پیش\u200cنویس\u200cها', 'پیش\u200cنویس\u200cها')], default='پیش\u200cنویس\u200cها', max_length=16, verbose_name='وضعیت')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.CreateModel(
            name='SendingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('منتشر شده', 'منتشر شده'), ('آرشیو شده', 'آرشیو شده'), ('پیش\u200cنویس\u200cها', 'پیش\u200cنویس\u200cها')], default='پیش\u200cنویس\u200cها', max_length=16, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('free_price', models.SmallIntegerField(verbose_name='جمع مبلغ خرید چقدر بود هزینه ارسال رایگان شود؟')),
                ('price', models.SmallIntegerField(verbose_name='مبلغ ارسال')),
                ('state', models.ManyToManyField(related_name='sending_methods', to='shop.state', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'طریقه ارسال محصول',
                'verbose_name_plural': 'طریقه ارسال محصول',
            },
        ),
    ]
