# Generated by Django 4.2.4 on 2023-12-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_state_sendingmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='status',
        ),
    ]
