# Generated by Django 4.2.4 on 2023-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0086_remove_state_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingmethod',
            name='free_price',
            field=models.SmallIntegerField(verbose_name='جمع مبلغ خرید چقدر بود هزینه ارسال رایگان شود؟(تومان)'),
        ),
        migrations.AlterField(
            model_name='sendingmethod',
            name='price',
            field=models.SmallIntegerField(verbose_name='مبلغ ارسال(تومان)'),
        ),
    ]
