# Generated by Django 4.2.4 on 2023-12-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0087_alter_sendingmethod_free_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingmethod',
            name='free_price',
            field=models.PositiveIntegerField(verbose_name='جمع مبلغ خرید چقدر بود هزینه ارسال رایگان شود؟(تومان)'),
        ),
    ]
