# Generated by Django 4.2.4 on 2023-12-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0088_alter_sendingmethod_free_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
