# Generated by Django 4.2.4 on 2023-12-31 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0089_remove_comment_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
        migrations.AddField(
            model_name='order',
            name='sending_method',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.sendingmethod', verbose_name='روش ارسال'),
            preserve_default=False,
        ),
    ]
