# Generated by Django 4.2.4 on 2024-01-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0090_remove_order_delivery_option_order_sending_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetech',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='brand',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='productattributestyle',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='productattributetech',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='productscollections',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2024/1', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='basic_gallery/images/2024/1', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2024/1', verbose_name='تصویر شاخص'),
        ),
    ]
