# Generated by Django 4.2.4 on 2024-01-04 12:35

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0091_attributestyle_position_attributetech_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت')),
                ('invoice_number', models.CharField(default=1000, max_length=128, unique=True, verbose_name='شماره قرارداد')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='shop.order', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'صورتحساب',
                'verbose_name_plural': 'صورتحساب ها',
            },
        ),
    ]
