# Generated by Django 4.2.4 on 2024-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0092_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributestyle',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
    ]
