# Generated by Django 4.2.4 on 2024-01-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0093_attributestyle_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscollections',
            name='child_position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='موقعیت زیردسته'),
        ),
    ]
