# Generated by Django 4.2.4 on 2024-01-14 06:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0095_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='guarantee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guarantee_conditions',
        ),
        migrations.AddField(
            model_name='brand',
            name='guarantee',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='گارانتی'),
        ),
        migrations.AddField(
            model_name='brand',
            name='guarantee_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='شرایط گارانتی'),
        ),
    ]
