# Generated by Django 4.2.4 on 2024-01-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0096_remove_product_guarantee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributestyle',
            options={'ordering': ['position'], 'verbose_name': 'مشخصات کلی', 'verbose_name_plural': 'مشخصات کلی'},
        ),
        migrations.AlterModelOptions(
            name='productattributestyle',
            options={'ordering': ['products_tag__position'], 'verbose_name': 'مشخصات کلی', 'verbose_name_plural': 'مشخصات کلی'},
        ),
    ]
