# Generated by Django 4.2.4 on 2024-02-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0097_alter_attributestyle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2024/2', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='basic_gallery/images/2024/2', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2024/2', verbose_name='تصویر شاخص'),
        ),
    ]
