# Generated by Django 4.2.4 on 2024-02-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0098_alter_brand_thumbnail_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingmethod',
            name='free_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='جمع مبلغ خرید چقدر بود هزینه ارسال رایگان شود؟(تومان)'),
        ),
        migrations.AlterField(
            model_name='sendingmethod',
            name='price',
            field=models.SmallIntegerField(blank=True, verbose_name='مبلغ ارسال(تومان)'),
        ),
    ]
