# Generated by Django 4.2.4 on 2024-02-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0099_alter_sendingmethod_free_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingmethod',
            name='price',
            field=models.IntegerField(verbose_name='مبلغ ارسال(تومان)'),
        ),
    ]
