# Generated by Django 4.2.4 on 2024-02-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0100_alter_sendingmethod_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در انتظار پرداخت', 'در انتظار پرداخت'), ('پرداخت موفق', 'پرداخت موفق'), ('در حال انجام', 'در حال انجام'), ('تکمیل شده', 'تکمیل شده'), ('مرجوع شده', 'مرجوع شده')], default='در انتظار پرداخت', max_length=64, verbose_name='وضعیت'),
        ),
    ]
