# Generated by Django 4.2.4 on 2024-02-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0103_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار پرداخت'), (1, 'پرداخت موفق'), (2, 'در حال انجام'), (3, 'تکمیل شده'), (4, 'مرجوع شده')], default=0, verbose_name='وضعیت'),
        ),
    ]
