# Generated by Django 4.2.4 on 2024-03-09 18:10

from django.db import migrations, models
from utils.general.models.model_status_abstract import Choices
from shop.models import Product


def update_choices(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for obj in Product.objects.all():
        if obj.status == 'پیش‌ فروش':
            obj.new_status = Choices.pre_order.value
        elif obj.status == 'در انبار موجود نیست':
            obj.new_status = Choices.out_stock.value
        elif obj.status == 'موجود در انبار':
            obj.new_status = Choices.in_stock.value
        obj.save()

def update_status_choices(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for obj in Product.objects.all():
        if obj.new_status == Choices.pre_order.value:
            obj.status = Choices.pre_order.value
        elif obj.new_status == Choices.out_stock.value:
            obj.status = Choices.out_stock.value
        elif obj.new_status == Choices.in_stock.value:
            obj.status = Choices.in_stock.value
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0106_alter_brand_thumbnail_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.RunPython(update_choices),
        migrations.AddField(
            model_name='product',
            name='new_status',
            field=models.IntegerField(choices=[(1, 'پیش\u200c فروش'), (2, 'در انبار موجود نیست'), (3, 'موجود در انبار')], default=3, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['status', '-updated_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(1, 'پیش\u200c فروش'), (2, 'در انبار موجود نیست'), (3, 'موجود در انبار')], default=3, max_length=32, verbose_name='وضعیت'),
        ),
        migrations.RunPython(update_status_choices),
    ]
