# Generated by Django 4.2.4 on 2024-03-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0107_alter_product_options_product_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'پیش\u200c فروش'), (2, 'در انبار موجود نیست'), (3, 'موجود در انبار')], default=3, max_length=32, verbose_name='وضعیت'),
        ),
    ]
