# Generated by Django 4.2.4 on 2024-04-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0111_alter_sendingmethod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consistency_code',
            field=models.CharField(blank=True, max_length=156, unique=True, verbose_name='کد پیگیری سفارش'),
        ),
    ]
