# Generated by Django 4.2.4 on 2024-04-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0112_alter_order_consistency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=156, verbose_name='متد پرداخت'),
        ),
    ]
