# Generated by Django 4.2.4 on 2024-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0114_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2024/5', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='basic_gallery/images/2024/5', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2024/5', verbose_name='تصویر شاخص'),
        ),
    ]
