# Generated by Django 4.2.4 on 2024-05-03 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0115_alter_brand_thumbnail_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRemider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remiders_product', to='shop.product', verbose_name='محصول')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remiders_user', to=settings.AUTH_USER_MODEL, verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'موجود شد خبر بده',
                'verbose_name_plural': 'موجود شد خبر بده',
            },
        ),
    ]
