# Generated by Django 4.2.4 on 2023-10-04 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='پرداختی')),
                ('cashback', models.PositiveIntegerField(default=0, verbose_name='مبلغ برگشتی هدیه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='خرید', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خرید محصول با کیف پول',
                'verbose_name_plural': 'خرید محصولات با کیف پول',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت')),
                ('balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودی')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی آپدیت')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شمسی ساخت')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ شمسی ساخت')),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Charge'), (2, 'Purchase')], default=1, verbose_name='نوع تراکنش')),
                ('amount', models.PositiveIntegerField(null=True, verbose_name='مبلغ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودی کیف پول'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='balance_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WalletPurchase',
        ),
    ]
