# Collection
from .base_collection import BaseCollectionSerializer
from .serializer_collection_list import CollectionListSerializer
from .serializer_collection_detail import CollectionDetailSerializer
from .serializer_collection_create_updated import CollectionCreateUpdateSerializer

# Product
from .base_products import BaseProductSerializer
from .serializer_products_detail import ProductDetailSerializer
from .serializer_products_list import ProductListSerializer, TorobProductSerializer
from .serializer_products_create_update import ProductCreateUpdateSerializer

# Discount
from .base_discount import BaseDiscountSerializer
from .serializer_discount_list import DiscountListSerializer
from .serializer_discount_detail import DiscountDetailSerializer
from .serializer_discount_create_update import DiscountCreateUpdateSerializer

# Comment
from .base_comments import BaseProductCommentSerializer
from .serializer_comment_list import CommentListSerializer
from .serializer_comment_detail import CommentDetailSerializer
from .serializer_comment_create_update import CommentCreateUpdateSerializer

# Order Item
from .serializer_order_item_list import OrderItemListSerializer
from .serializer_order_detail import OrderDetailSerializer
from .serializer_order_item_create_update import OrderItemCreateUpdateSerializer
from .base_order_item import BaseOrderItemSerializer

# Order
from .base_order import BaseOrderSerializer
from .serializer_order_list import OrderListSerializer
from .serializer_order_create_update import OrderCreateUpdateSerializer

# Brand
from .base_brand import BaseBrandSerializer
from .serializer_brand_create_update import BrandCreateUpdateSerializer
from .serializer_brand_detail import BrandDetailSerializer
from .serializer_brand_list import BrandListSerializer

# Branch
from .base_branch import BaseBranchSerializer
from .serializer_branch_create_update import ProductBranchCreateUpdateSerializer, MainBranchSerializer
from .serializer_branch_detail import BranchDetailSerializer
from .serializer_branch_list import BranchListSerializer

# Tag
from .base_special_tag import BaseSpecialTagSerializer
from .serializer_special_tag_create_update import SpecialTagCreateUpdateSerializer
from .serializer_special_tag_detail import SpecialTagDetailSerializer
from .serializer_special_tag_list import SpecialTagListSerializer

# Suggestions
from .base_suggestions import BaseSuggestionsSerializer
from .serializer_suggestion_detail import SuggestionDetailSerializer
from .serializer_suggestion_list import SuggestionListSerializer
from .serializer_suggestion_create_update import SuggestionCreateUpdateSerializer

# Colors
from .base_colors import BaseColorsSerializer
from .serializer_colors_create_update import ColorCreateUpdateSerializer
from .serializer_colors_detail import ColorDetailSerializer
from .serializer_colors_list import ColorListSerializer

# Attributes
from .base_attributes import BaseAttributeStyleSerializer, BaseAttributeTechSerializer
from .serializer_attributes_create_update import ProductAttributeStyleCreateUpdateSerializer, \
    ProductAttributeTechCreateUpdateSerializer
from .serializer_attributes_detail import AttributeStyleDetailSerializer, AttributeTechDetailSerializer
from .serializer_attributes_list import AttributeStyleListSerializer, AttributeTechListSerializer

# Gallery
from .base_gallery import BaseGallerySerializer

from .base_set_watch import SetWatchSerializer

# State
from .base_state import BaseStateSerializer

# Sending Method
from .serializer_sending_method_detail import SendingMethodDetailSerializer
from .serializer_sending_method_list import SendingMethodListSerializer
from .serializer_sending_method_create_update import SendingMethodCreateUpdateSerializer
from .base_sending_method import BaseSendingMethodSerializer

# Import/Export data
from .serializer_impoer_data_in_product import ImportDataInProductSerializer

# invoice
from .serializer_invoice_detail import InvoiceDetailSerializer
from .serializer_invoice_list import InvoiceListSerializer
from .serialzier_order_item_for_invoce import OrderItemForInvoiceSerializer
from .serialzier_sending_method_for_invoice import SendingMethodForInvoiceSerializer

from .base_reminder import BaseProductRemiderSerializer, CreateProductRemiderSerializer
