# Generated by Django 4.2.4 on 2023-11-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_colors_alter_option_colors'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
